swagger: "2.0"
info:
  title: Fileactive NPP Payment API
  description: Fileactive NPP Payment API.
  version: 1.0.2.11
host: api.fileactive.uat.anzgcis.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /npp/v1.0/payment/submit:
    post:
      tags:
        - Payment
      summary: Submit Payment
      description: Payment initiation request related to a single credit transfer
        between a debtor and creditor.
      operationId: submitPayment
      externalDocs:
        description: Error and Event Codes
        url: "https://anz-insto.github.io/fileactive/event-codes.html"
      parameters:
        - name: x-Correlation-Id
          in: header
          description: Optional correlation ID provided by the data consumer that should
            be reflected back in the response headers. Can be used for reporting
            and logging.
          required: false
          type: string
          format: uuid
        - name: x-Message-Id
          in: header
          description: Duplicate check using point to point reference, as assigned by the
            instructing party, and sent to the next party in the chain to
            unambiguously identify the message. X-Message-Id will be used as the
            {transaction_identification} parameter to retrieve payment status.
          required: true
          type: string
          format: uuid
        - in: body
          name: secured_pain001
          description: "Secured resource to instruct movement of funds from the debtor
            account to creditor, object:
            #/definitions/PaymentSubmissionResource"
          required: true
          schema:
            $ref: "#/definitions/SecuredPaymentSubmissionResource"
          x-jws-signature:
            algorithm: RS256
          x-jwe-encryption:
            algorithm: RSA-OAEP
            encryption: A256CBC-HS512
      responses:
        "201":
          description: Success - Payment request resource created
          headers:
            x-Correlation-Id:
              type: string
              format: uuid
              description: Optional consumer provided Correlation-Id, echo'd from request.
            x-RequestKey:
              type: string
              format: uuid
              description: Request Key provided to customer for support and reporting
                purposes.
            Location:
              description: Location of the resource
              type: string
          schema:
            $ref: "#/definitions/PaymentSubmitResource"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorCode"
          headers:
            Location:
              description: Location of the duplicate resource where applicable
              type: string
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "405":
          description: Method Not Allowed
          schema:
            $ref: "#/definitions/ErrorCode"
        "429":
          description: Too many requests
        "500":
          description: Internal Server Error
        "502":
          description: Bad Gateway
        "503":
          description: Service Unavailable
        "504":
          description: Gateway Timeout
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorCode"
      security:
        - apiKey: []
          OAuth2: []
  "/npp/v1.0/payment/{transaction_identification}/status":
    get:
      tags:
        - Payment
      summary: Get Payment Status
      description: Request sent by a OSP (Overlay Service Provider) in order to get
        the status of a given transaction.
      operationId: getPaymentStatus
      parameters:
        - name: transaction_identification
          in: path
          description: Unique identification, as assigned by the first instructing agent,
            to unambiguously identify the transaction that is passed on,
            unchanged, throughout the entire interbank chain.
          required: true
          type: string
        - name: x-Correlation-Id
          in: header
          description: Optional correlation ID provided by the data consumer that should
            be reflected back in the response headers. Can be used for reporting
            and logging.
          required: false
          type: string
      responses:
        "200":
          description: Resource to report the status of a customer credit transfer.
          headers:
            x-Correlation-Id:
              type: string
              description: Optional correlation ID provided by the data consumer that should
                be reflected back in the response headers.
          schema:
            $ref: "#/definitions/PaymentStatusResource"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorCode"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "429":
          description: Too many requests
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorCode"
        "502":
          description: Bad Gateway
        "503":
          description: Service Unavailable
        "504":
          description: Gateway Timeout
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorCode"
      security:
        - apiKey: []
          OAuth2: []
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: apikey
    description: API key to authorize requests.
  OAuth2:
    type: oauth2
    description: ANZâ€™s OAuth 2.0 API is used for authentication and authorization
      and is OpenID Connect compliant, please refer to this site's oAuth2 page
    flow: implicit
    authorizationUrl: https://api.fileactive.uat.anzgcis.com/v1.0/auth
    scopes:
      AU.INSTO.PAYMENT.NPP.CREATE: Create an NPP Payment
      AU.INSTO.PAYMENT.NPP.READ: Get the status of an NPP Payment
definitions:
  ErrorCode:
    type: object
    required:
      - status
    properties:
      status:
        type: object
        required:
          - code
          - severity
          - text
        properties:
          severity:
            type: string
            enum:
              - Fatal
              - Transient
          code:
            type: string
          text:
            type: string
        example:
          severity: Fatal
          code: EC00X_XXX
          text: ERROR TEXT HERE
  PaymentSubmitResource:
    type: object
    required:
      - transaction_status
    properties:
      transaction_status:
        type: string
        example: RCVD
        description: "Specifies the status of a transaction, in a coded form. RCVD -
          RECEIVED \r

          \ ACTC - ACCEPTED \r

          \ ACSC - SETTLED \r

          \ RJCT - REJECTED"
        enum:
          - RCVD
          - RJCT
  PaymentSubmissionResource:
    type: object
    required:
      - creation_date_time
      - creditor_agent_bic
      - creditor_name
      - debtor_name
      - end_to_end_identification
      - initiating_party_name
      - instructed_amount
      - instruction_identification
      - requested_execution_date
    properties:
      instruction_identification:
        type: string
        example: TC121/1471873823
        description: Unique identification as assigned by an instructing party for an
          instructed party to unambiguously identify the instruction.
        minLength: 1
        maxLength: 35
      end_to_end_identification:
        type: string
        example: BILL00237679
        description: Unique identification assigned by the initiating party to
          unambiguously identify the transaction. This identification is passed
          on, unchanged, throughout the entire end-to-end chain.
        minLength: 1
        maxLength: 35
      creation_date_time:
        type: string
        example: 2018-07-17T09:30:47Z
        description: Date and time at which the request was created.
        pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.[0-9]+)?(?:Z|[+-][01]\d:[0-5]\d)?$
      initiating_party_name:
        type: string
        example: HITACHI INTERNATIONAL
        description: Name by which the Initiating Party is known and which is usually
          used to identify that party.
        minLength: 1
        maxLength: 140
      initiating_party_bic:
        type: string
        example: HITLSGSG
        description: Code allocated to a financial or non-financial institution by the
          ISO 9362 Registration Authority, as described in ISO 9362 "Banking -
          Banking telecommunication messages - Business identifier code (BIC)".
        pattern: ^[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}$
      instruction_priority:
        type: string
        example: NORM
        description: Indicator of the urgency or order of importance that the
          instructing party would like the instructed party to apply to the
          processing of the instruction.
        enum:
          - HIGH
          - NORM
      service_level:
        type: string
        example: npp.clear.01-x2p1
        description: Specifies a pre-agreed service or level of service between the
          parties, as a proprietary code.
        minLength: 1
        maxLength: 35
      local_instrument:
        type: string
        example: TRF
        description: Specifies the local instrument, as published in an external local
          instrument code list.
      category_purpose:
        type: string
        example: SSBE
        description: Category purpose, as published in an external category purpose code
          list.
      requested_execution_date:
        type: string
        example: 2018-09-17
        description: Specified date.
        pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$
      debtor_name:
        type: string
        example: BILBO BAGGINS
        description: Name by which a party is known and which is usually used to
          identify that party.
        minLength: 1
        maxLength: 140
      debtor_alias_type:
        type: string
        example: TELI
        description: "Contains the type of Alias Identifier. \r

          \ TELI - TELEPHONE NUMBER \r

          \ EMAL - EMAIL ADDRESS \r

          \ AUBN - AUSTRALIAN BUSINESS NUMBER \r

          \ ORGN - ORGANISATION ID"
        enum:
          - TELI
          - EMAL
          - AUBN
          - ORGN
      debtor_alias_value:
        type: string
        example: +61-4235678654
        description: Contains the actual value for the supplied type, so an email
          address, a phone number etc. Refer to Alias Processing section for
          more detail
        minLength: 1
        maxLength: 2048
      debtor_account_identification:
        type: string
        example: "833421234567"
        description: Unique and unambiguous identification for the account between the
          account owner and the account servicer.
        minLength: 1
        maxLength: 34
      debtor_account_type:
        type: string
        example: BBAN
        description: "Name of the account identification identification scheme. \r

          \ BBAN - BSB and ACCOUNT NUMBER \r

          \ AIIN - CREDIT CARD"
        enum:
          - BBAN
          - AIIN
      debtor_agent_bic:
        type: string
        example: ANZBAU33XXX
        description: Code allocated to a financial or non-financial institution by the
          ISO 9362 Registration Authority, as described in ISO 9362 "Banking -
          Banking telecommunication messages - Business identifier code (BIC)".
        pattern: ^[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}$
      instructed_amount:
        $ref: "#/definitions/CurrencyAndAmount"
      creditor_name:
        type: string
        example: SAMWISE GAMGEE
        description: Name by which a party is known and which is usually used to
          identify that party.
        minLength: 1
        maxLength: 140
      creditor_alias_type:
        type: string
        example: TELI
        description: "Contains the type of Alias Identifier. \r

          \ TELI - TELEPHONE NUMBER \r

          \ EMAL - EMAIL ADDRESS \r

          \ AUBN - AUSTRALIAN BUSINESS NUMBER \r

          \ ORGN - ORGANISATION ID"
        enum:
          - TELI
          - EMAL
          - AUBN
          - ORGN
      creditor_alias_value:
        type: string
        example: +61-4123456789
        description: Contains the actual value for the supplied type, so an email
          address, a phone number etc. Refer to Alias Processing section for
          more detail./
        minLength: 1
        maxLength: 2048
      creditor_account_identification:
        type: string
        example: "62016987654321"
        description: Unique and unambiguous identification for the account between the
          account owner and the account servicer.
        minLength: 1
        maxLength: 34
      creditor_account_type:
        type: string
        example: BBAN
        description: "Name of the account identification identification scheme \r

          \ BBAN - BSB and ACCOUNT NUMBER \r

          \ AIIN - CREDIT CARD"
        enum:
          - BBAN
          - AIIN
      creditor_agent_bic:
        type: string
        example: ANZBAU3MXXX
        description: Code allocated to a financial or non-financial institution by the
          ISO 9362 Registration Authority, as described in ISO 9362 "Banking -
          Banking telecommunication messages - Business identifier code (BIC)".
        pattern: ^[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}$
      remittance_referred_document_type:
        type: string
        example: CINV
        description: Specifies the type of referred document.
        minLength: 1
        maxLength: 35
      remittance_referred_document_number:
        type: string
        example: INV-12345678
        description: Unique and unambiguous identification of the referred document.
        minLength: 1
        maxLength: 35
      remittance_referred_related_date:
        type: string
        example: 2018-08-23
        description: Date associated with the referred document.
        pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$
      remittance_information_unstructured:
        type: array
        example: FIRST LINE SECOND LINE
        description: Information supplied to enable the matching/reconciliation of an
          entry with the items that the payment is intended to settle, such as
          commercial invoices in an accounts' receivable system, in an
          unstructured form.
        items:
          type: string
          minLength: 1
          maxLength: 140
        maxItems: 2
    description: "Resource to instruct movement of funds from the debtor account to
      creditor. "
    example:
      service_level: npp.clear.01-x2p1
      instruction_identification: TC121/1471873823
      end_to_end_identification: NOTPROVIDED
      creation_date_time: 2018-09-17T09:45:47Z
      initiating_party_name: HITACHI INTERNATIONAL
      initiating_party_bic: HITLSGSG
      instruction_priority: HIGH
      local_instrument: TRF
      category_purpose: SSBE
      requested_execution_date: 2018-09-17
      debtor_name: BILBO BAGGINS
      debtor_account_identification: "013434992345677"
      debtor_account_type: BBAN
      debtor_agent_bic: ANZBAU3MXXX
      instructed_amount:
        currency: AUD
        amount: "562.89"
      creditor_name: SAMWISE GAMGEE
      creditor_alias_type: TELI
      creditor_alias_value: +61-4123456789
      creditor_account_identification: "62016987654321"
      creditor_account_type: BBAN
      creditor_agent_bic: NOTPROVIDED
      remiitance_referred_document_type: CINV
      remittance_referred_document_number: INV-12345678
      remittance_referred_related_date: 2018-08-23
      remittance_information_unstructured:
        - FIRST LINE
        - SECOND LINE
  CurrencyAndAmount:
    type: object
    required:
      - amount
      - currency
    properties:
      currency:
        $ref: "#/definitions/CurrencyCode"
      amount:
        type: string
        example: "562.89"
        description: A number of monetary units specified in an active or a historic
          currency where the unit of currency is explicit and compliant with ISO
          4217.
        maxLength: 19
  CurrencyCode:
    type: string
    pattern: ^[A-Z]{3,3}$
    description: A code allocated to a currency by a Maintenance Agency under an
      international identification scheme, as described in the latest edition of
      the international standard ISO 4217 "Codes for the representation of
      currencies and funds".
    example: AUD
  PaymentStatusResource:
    type: object
    required:
      - transaction_status
    properties:
      transaction_status:
        type: string
        example: ACTC
        description: "Specifies the status of a transaction, in a coded form. RCVD -
          RECEIVED \r

          \ ACTC - ACCEPTED \r

          \ ACSC - SETTLED \r

          \ RJCT - REJECTED"
        enum:
          - RCVD
          - ACTC
          - ACSC
          - RJCT
      transaction_status_reason_code:
        type: string
        example: AC01
        description: Reason for the status, as published in an external reason code list.
      transaction_status_description:
        type: string
        example: Incorrect Account Number
        description: "Further details on the status reason. "
        minLength: 1
        maxLength: 105
      transaction_identification:
        type: string
        example: 2dafb4db-f2fd-4af8-8e33-2715a59dd529
        description: Unique identification, as assigned by the first instructing agent,
          to unambiguously identify the transaction that is passed on,
          unchanged, throughout the entire interbank chain.
        minLength: 1
        maxLength: 36
      acceptance_datetime:
        type: string
        example: 2018-03-22T12:45:08Z
        description: Point in time when the payment order from the initiating party
          meets the processing conditions of the account servicing agent. This
          means that the account servicing agent has received the payment order
          and has applied checks such as authorisation, availability of funds.
        pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.[0-9]+)?(?:Z|[+-][01]\d:[0-5]\d)?$
    description: Resource to report the status of a customer credit transfer.
    example:
      transaction_identification: 32d292f1-ee65-11ea-84ce-3d837763b9eb
      transaction_status: ACTC
      transaction_status_description: Processing
      acceptance_date_time: 2020-09-04T04:15:04.631Z
  SecuredPaymentSubmissionResource:
    type: object
    properties:
      secured_pain001:
        type: string
        description: "Pain001: PaymentSubmissionResource"
  uuid:
    type: string
    example: 2dafb4db-f2fd-4af8-8e33-2715a59dd529
    description: UUID REGEX Pattern
      [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
    pattern: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

tags:
  - name: Payments
    description: |
      Operations related to Australian NPP payments.
  - name: PaymentSubmissionResource
    description: <SchemaDefinition schemaRef="#/components/schemas/PaymentSubmissionResource" />
    x-displayName: PaymentSubmissionResource
  - name: PaymentStatusResource
    description: <SchemaDefinition schemaRef="#/components/schemas/PaymentStatusResource" />
    x-displayName: PaymentStatusResource
x-tagGroups:
  - name: Paths
    tags: 
      - Payment
  - name: Models
    tags: 
      - PaymentSubmissionResource
      - PaymentStatusResource
